project:
  title: "PSC-012Y Unit 4"
  type: default
  output-dir: output
  render:
    - unit-04-continuous.qmd

format:
  html:
    toc: true
    number-sections: true
    embed-resources: true

editor: visual
