project:
  title: "PSC-012Y Unit 7"
  type: default
  output-dir: output
  render:
    - unit-07-text-data.qmd

format:
  html:
    toc: true
    number-sections: true
    embed-resources: true

editor: visual
